import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerCodegenGeneratePayload } from './generate-payload.js';
import { registerCodegenValidatePayload } from './validate-payload.js';
import { registerCodegenDiffPayload } from './diff-payload.js';
import { registerCodegenSyncPayload } from './sync-payload.js';
import { registerCodegenMigratePayload } from './migrate-payload.js';
import { registerCodegenGetFieldValidationCatalog } from './get-field-validation-catalog.js';
import { registerCodegenGetQueryDeclarativeCatalog } from './get-query-declarative-catalog.js';
import { registerCodegenGetDashboardCatalog } from './get-dashboard-catalog.js';
import { registerCodegenCreateEndpoint } from './create-endpoint.js';
import { registerCodegenCreateDashboard } from './create-dashboard.js';
import { registerCodegenCreateProcessor } from './create-processor.js';
import { registerCodegenCreateKafkaConsumer } from './create-kafka-consumer.js';
import { registerCodegenGenerateTest } from './generate-test.js';
import { registerCodegenValidateDashboardPayload } from './validate-dashboard-payload.js';
import { registerCodegenListTables } from './list-tables.js';
import { registerCodegenDescribeTable } from './describe-table.js';
import { registerCodegenValidateSql } from './validate-sql.js';
import { registerCodegenGetDbschemaCatalog } from './get-dbschema-catalog.js';
import { registerCodegenDbschemaInit } from './dbschema-init.js';
import { registerCodegenDbschemaValidate } from './dbschema-validate.js';
import { registerCodegenDbschemaModels } from './dbschema-models.js';
import { registerCodegenDbschemaGenerateDdl } from './dbschema-generate-ddl.js';
import { registerCodegenDbschemaIntrospect } from './dbschema-introspect.js';
import { registerCodegenDbschemaMigrate } from './dbschema-migrate.js';
import { registerCodegenDbschemaDiff } from './dbschema-diff.js';
import { registerCodegenDbschemaApply } from './dbschema-apply.js';
import { registerCodegenDbschemaTemplate } from './dbschema-template.js';

export function registerCodegenTools(server: McpServer): void {
  registerCodegenGeneratePayload(server);
  registerCodegenValidatePayload(server);
  registerCodegenDiffPayload(server);
  registerCodegenSyncPayload(server);
  registerCodegenMigratePayload(server);
  registerCodegenGetFieldValidationCatalog(server);
  registerCodegenGetQueryDeclarativeCatalog(server);
  registerCodegenGetDashboardCatalog(server);
  registerCodegenCreateEndpoint(server);
  registerCodegenCreateDashboard(server);
  registerCodegenCreateProcessor(server);
  registerCodegenCreateKafkaConsumer(server);
  registerCodegenGenerateTest(server);
  registerCodegenValidateDashboardPayload(server);
  registerCodegenListTables(server);
  registerCodegenDescribeTable(server);
  registerCodegenValidateSql(server);
  registerCodegenGetDbschemaCatalog(server);
  registerCodegenDbschemaInit(server);
  registerCodegenDbschemaValidate(server);
  registerCodegenDbschemaModels(server);
  registerCodegenDbschemaGenerateDdl(server);
  registerCodegenDbschemaIntrospect(server);
  registerCodegenDbschemaMigrate(server);
  registerCodegenDbschemaDiff(server);
  registerCodegenDbschemaApply(server);
  registerCodegenDbschemaTemplate(server);
}
